### ISSUE TITLE
No response, no error

### ISSUE THREAD

**Issue by trebiluk** [dmhacker/alexa-youtube-skill#12]
Have built and rebuilt this skill with no luck.

2017-08-20T19:05:37.402Z	8d0ddc6b-85da-11e7-856b-930b9b388846	Unhandled rejection Error: Invalid application
at Object.ensureErrorObject (/var/task/node_modules/bluebird/js/main/util.js:261:20)
at Promise._rejectCallback (/var/task/node_modules/bluebird/js/main/promise.js:472:22)
at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/main/promise.js:516:17)
at Promise._settlePromiseAt (/var/task/node_modules/bluebird/js/main/promise.js:584:18)
at Promise._settlePromiseAtPostResolution (/var/task/node_modules/bluebird/js/main/promise.js:248:10)
at Async._drainQueue (/var/task/node_modules/bluebird/js/main/async.js:128:12)
at Async._drainQueues (/var/task/node_modules/bluebird/js/main/async.js:133:10)
at Immediate.Async.drainQueues (/var/task/node_modules/bluebird/js/main/async.js:15:14)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by dmhacker** [comment]
What Node version are you using?

**Comment by trebiluk** [comment]
Two things:
1) changed the invocation from youtube to something else
2) changed to node 4.3 (did this the 2nd time but forgot on the 3rd)

Working now - thanks for the reply.

I think my Firestick Youtube app was interfering as well.
