### ISSUE TITLE
Unhandle rejection Error: Invalid application

### ISSUE THREAD

**Issue by VerHext** [dmhacker/alexa-youtube-skill#16]
Hello,

i want to install this skill today on a aws lambda.
This lambda is in EU ireland and use NodeJs 4.3

I want to start a small lambda test. I get follwing error:

```
2017-11-22T22:01:03.122Z	a1af59bf-cfd0-11e7-91cc-739af6785e91	Unhandled rejection Error: Invalid application
    at Object.ensureErrorObject (/var/task/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/var/task/node_modules/bluebird/js/main/promise.js:472:22)
    at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/main/promise.js:516:17)
    at Promise._settlePromiseAt (/var/task/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/var/task/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/var/task/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/var/task/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/task/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

I hope you can help me 👍

**Comment by TheDroide** [comment]
@VerHext I am getting the exact same error, how did you solve it?
