### ISSUE TITLE
not working for me at all

### ISSUE THREAD

**Issue by drizzt09** [dmhacker/alexa-youtube-skill#25]
when i test from skill:
echo, search YouTube for Frost Hyperventilate.
or
search YouTube for Frost Hyperventilate.
Frost Hyperventilate.
 i get the same lamda response:
{
  "version": "1.0",
  "response": {
    "speechletResponse": {
      "directives": [],
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}
 When i ask my echo directly:
echo, search YouTube for Frost Hyperventilate.
It just turns off the blue light
When I ask echo directly:
echo, ask YouTube to search for Frost Hyperventilate.'I get response im sorry i dont know what went wrong

**Comment by dmhacker** [comment]
Are you sure you gave the skill the correct ARN? And is skill testing enabled for your account?

**Comment by Boar007** [comment]
same for me
test results:
Response:
{
  "errorMessage": "RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd Process exited before completing request"
}

Request ID:
"dfea431a-0ea3-11e8-9b39-57237427abcd"

Function Logs:
START RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd Version: $LATEST
2018-02-10T20:49:23.567Z	dfea431a-0ea3-11e8-9b39-57237427abcd	Searching ... cro
2018-02-10T20:49:24.384Z	dfea431a-0ea3-11e8-9b39-57237427abcd	SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/var/task/index.js:103:29)
    at Request.self.callback (/var/task/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/task/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)
END RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd
REPORT RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd	Duration: 1002.18 ms	Billed Duration: 1100 ms 	Memory Size: 128 MB	Max Memory Used: 45 MB	
RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd Process exited before completing request

**Comment by dmhacker** [comment]
Stale issue. Closing.
