### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Boar007** [dmhacker/alexa-youtube-skill#28]
when testing I got the message:
The remote endpoint could not be called, or the response it returned was invalid.

By testing in Lambda AWS I got the execution results:

Response:
{
  "errorMessage": "RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd Process exited before completing request"
}

Request ID:
"dfea431a-0ea3-11e8-9b39-57237427abcd"

Function Logs:
START RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd Version: $LATEST
2018-02-10T20:49:23.567Z	dfea431a-0ea3-11e8-9b39-57237427abcd	Searching ... cro
2018-02-10T20:49:24.384Z	dfea431a-0ea3-11e8-9b39-57237427abcd	SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/var/task/index.js:103:29)
    at Request.self.callback (/var/task/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/task/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)
END RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd
REPORT RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd	Duration: 1002.18 ms	Billed Duration: 1100 ms 	Memory Size: 128 MB	Max Memory Used: 45 MB	
RequestId: dfea431a-0ea3-11e8-9b39-57237427abcd Process exited before completing request

**Comment by freakonsonic** [comment]
Same issue here. It seems [https://dmhacker-youtube.herokuapp.com](https://dmhacker-youtube.herokuapp.com) is currently (?) not available. The site just tells 

> Application error

> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

Can we pass another value to HEROKU_APP_URL parameter to point to a running intermediary server?

**Comment by Boar007** [comment]
Ok now after the https://dmhacker-youtube.herokuapp.com is working.

**Comment by dmhacker** [comment]
This is an issue with https://github.com/dmhacker/dmhacker-youtube. Closing becaues the website should be running now.
