### ISSUE TITLE
Unhandled rejection Error: Invalid application

### ISSUE THREAD

**Issue by sam170582** [dmhacker/alexa-youtube-skill#5]
I just took the recent code from master. 
When testing lamda function, I am getting this error:

```
Unhandled rejection Error: Invalid application
 at Object.ensureErrorObject (/var/task/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/var/task/node_modules/bluebird/js/main/promise.js:472:22)
    at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/main/promise.js:516:17)
    at Promise._settlePromiseAt (/var/task/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/var/task/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/var/task/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/var/task/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/var/task/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by andrewdavisdev** [comment]
@dmhacker  I am also getting this error message on the Lambda Function.

**Comment by dmhacker** [comment]
@sam170582  @andrewdavisdev Can you guys try downloading the latest file from [this link](https://s3-us-west-1.amazonaws.com/alexa-youtube-skill/lambda/alexa-youtube-skill.zip) and uploading that (rather than compiling it yourselves)? Also, make sure your environment variables are set up properly.

**Comment by Firni95** [comment]
I set up everything with the new zip and now the skill found a song, but isn't able to play it.
Maybe its becouse of my location (Germany) and Lambda doesn't allow alexa skills from germany so I used Ireland instead?!

Do you still need an S3 bucket?

Log:
START RequestId: 07da3085-768f-11e7-a843-c7fba42a9edb Version: $LATEST
2017-08-01T07:57:14.497Z	07da3085-768f-11e7-a843-c7fba42a9edb	Searching ... maffay
2017-08-01T07:57:15.699Z	07da3085-768f-11e7-a843-c7fba42a9edb	Found ... Peter Maffay - Wenn Der Himmel Weint (Offizielles Video)
2017-08-01T07:57:16.358Z	07da3085-768f-11e7-a843-c7fba42a9edb	Processed.
2017-08-01T07:57:16.754Z	07da3085-768f-11e7-a843-c7fba42a9edb	Stored @ undefined
END RequestId: 07da3085-768f-11e7-a843-c7fba42a9edb
REPORT RequestId: 07da3085-768f-11e7-a843-c7fba42a9edb	Duration: 2462.19 ms	Billed Duration: 2500 ms Memory Size: 128 MB	Max Memory Used: 40 MB

**Comment by dmhacker** [comment]
You shouldn't need an S3 bucket. That is handled by my server. What's happening is you are timing out. Under Advanced Settings on your lambda machine, increase the timeout to >= 1 minute.

http://i.imgur.com/BKEJKdt.png

**Comment by dmhacker** [comment]
Closing this issue because everything seems to have been fixed here.
